version: '3.7'

services:
  samba:
    build: .
    container_name: samba_server
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - ./shared:/shared
      - ./logs:/var/log/samba
    restart: unless-stopped
