- name: Update haproxy config file
  hosts: haproxy
  become: true
  tasks:
    - name: Add server webserv3 to loadbalancer
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        line: "\t\tserver webserv3 NEW_SERVER_IP_ADDRESS:80"
        insertafter: "^server webserv2"
        state: present
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted
